argue: implement an option to set a command to fetch a value

diff --git a/translight b/translight
--- a/translight
+++ b/translight
@@ -9,17 +9,18 @@ guide() {
 	echo 'Guide:'
 }
 
-get-selection() {
-	local expression=$(xsel -o);
-	echo "${expression%\*}"
-}
-
 install() {
 	if (argue-setup); then
-		apt install -y jq wget xsel libnotify-bin
+		command -v apt && \
+		apt install -y jq wget xsel libnotify-bin && \
 		wget https://translate.google.ru/favicon.ico -O $icon_path
 	fi
 	exit $?
+}
+
+get-selection() {
+	local expression=$(xsel -o 2> /dev/null)
+	echo "${expression%\*}"
 }
 
 join() {
@@ -42,9 +43,11 @@ argue internal usage of usage \
 	as 'Print short usage'
 argue internal "setup|install" of setup do install \
 	as 'Install auto completion and other dependancies'
-argue optional --selection to do_selection = true or false \
-	as 'Translate selected expression'
-argue optional --expression of EXPRESSION to expression ~ ".+" \
+if command -v xsel &> /dev/null; then
+	argue optional --selection to expression : get-selection \
+		as 'Translate selected expression'
+fi
+argue optional --expression of EXPRESSION to expression ~ ".+" or "$expression" \
 	as 'Translate supplied expression'
 argue optional --language of LANGUAGE to language ~ "[a-z]{2}" or ru \
 	as 'Language to translate to'
@@ -55,16 +58,15 @@ argue optional --notify to do_notify = true or false \
 (($? >= 200)) && echo && exit
 argue %% 'Unknown arguments {} will be ignored'
 
-if $do_selection; then
-	expression=$(get-selection)
-fi
 if [[ -z $expression ]]; then
 	echo "Expression is empty"
 	exit 1
 fi
 
 link="http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=$language&dt=t&dt=qca&dt=bd&dj=1&q=$expression"
-json=$(wget -U "Mozilla/5.0" -qO - "$link")
+if ! json=$(wget -U "Mozilla/5.0" -qO - "$link" 2> /dev/null); then
+	echo 'Cannot connect to Google Translate server'; exit 1
+fi
 
 correction=$(echo $json | jq -r '.sentences[0].orig')
 translation=$(echo $json | jq -r '.sentences[0].trans')
